---
# Bootstrap webservers
- hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest

    - name: Create html directory if it does not exist
      file:
        path: /var/www/html
        state: directory

    - name: Create index.html file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Add web content
      lineinfile:
        line: "Here is some text"
        path: /var/www/html/index.html

    - name: Start httpd
      service:
        name: httpd
        state: started

## In this case the code will be : 
## ansible-playbook -i inv web.yml
